// AUTO-GENERATED by tools/gen-registries.ts — DO NOT EDIT BY HAND.
// Type-safe corps identities (PLAN §3.1). Source: prod corps registry snapshot.
// Regenerate: DCI_DB=/path/to/dci-relational.db npx tsx tools/gen-registries.ts
import type { Corps } from './domain.js';

/** PascalCase identifier → frozen {@link Corps} instance. Includes the Unknown sentinel. */
export const GENERATED_CORPS = {
  Alliance: { key: "001j000000iwwsmaal", name: "Alliance", division: "All Age" },
  Arsenal: { key: "arsenal", name: "Arsenal", division: "Open Class" },
  AtlantaCV: { key: "001j000000iwwsnaal", name: "Atlanta CV", division: "All Age" },
  Beijing57HighSchool: { key: "beijing-57-high-school", name: "Beijing 57 High School", division: "World Class" },
  Bluecoats: { key: "001j000000iwwsraal", name: "Bluecoats", division: "World Class" },
  BlueDevils: { key: "001j000000i6i9saav", name: "Blue Devils", division: "World Class" },
  BlueDevilsB: { key: "001j000000i6jmbaaf", name: "Blue Devils B", division: "Open Class" },
  BlueDevilsC: { key: "001j000000i6kalaa3", name: "Blue Devils C", division: "Open Class" },
  BlueKnights: { key: "001j000000iwwsoaal", name: "Blue Knights", division: "World Class" },
  BlueSaints: { key: "001j000000iwwspaal", name: "Blue Saints", division: "Open Class" },
  BlueStars: { key: "001j000000iwwsqaal", name: "Blue Stars", division: "World Class" },
  BostonCrusaders: { key: "001j000000iwwssaal", name: "Boston Crusaders", division: "World Class" },
  Bushwackers: { key: "bushwackers-drum-corps", name: "Bushwackers", division: "All Age" },
  Cadets2: { key: "0010a00001iprmyaah", name: "Cadets 2", division: "All Age" },
  CalgaryRoundUpBand: { key: "calgary-round-up-band", name: "Calgary Round-Up Band", division: "Open Class" },
  CalgaryStampedeShowband: { key: "001j000000jtq2zaad", name: "Calgary Stampede Showband", division: "World Class" },
  CarolinaCrown: { key: "001j000000iwx91aad", name: "Carolina Crown", division: "World Class" },
  CarolinaGold: { key: "001j000000iwx92aad", name: "Carolina Gold", division: "All Age" },
  ChienKuo: { key: "chien-kuo", name: "Chien Kuo", division: "World Class" },
  CincinnatiTradition: { key: "001j000000iwx94aad", name: "Cincinnati Tradition", division: "All Age" },
  CitySound: { key: "city-sound", name: "City Sound", division: "Open Class" },
  CoastalSurge: { key: "001j000000iwx96aad", name: "Coastal Surge", division: "Open Class" },
  ColtCadets: { key: "001j000000iwx97aad", name: "Colt Cadets", division: "Open Class" },
  Colts: { key: "001j000000iwx98aad", name: "Colts", division: "World Class" },
  Columbians: { key: "001j000000iwx99aad", name: "Columbians", division: "Open Class" },
  ColumbusSaints: { key: "001j000000hiripaaz", name: "Columbus Saints", division: "All Age" },
  ConnecticutHurricanes: { key: "0015b00002eebx5aaf", name: "Connecticut Hurricanes", division: "All Age" },
  Crossmen: { key: "001j000000iwx9aaat", name: "Crossmen", division: "World Class" },
  Encorps: { key: "encorps", name: "Encorps", division: "Open Class" },
  ErieThunderbirds: { key: "0010a000019s6ceaay", name: "Erie Thunderbirds", division: "All Age" },
  Eruption: { key: "001j000000iwx9daat", name: "Eruption", division: "Open Class" },
  FusionCore: { key: "001j000000gbtqyaac", name: "Fusion Core", division: "All Age" },
  Genesis: { key: "001j000000iwx9oaad", name: "Genesis", division: "World Class" },
  GitaSurosowanBanten: { key: "gita-surosowan-banten", name: "Gita Surosowan Banten", division: "World Class" },
  Gold: { key: "001j000000iwx9paad", name: "Gold", division: "Open Class" },
  GoldenEmpire: { key: "001j000000iwx9qaad", name: "Golden Empire", division: "Open Class" },
  Govenaires: { key: "001j000000iwx9raad", name: "Govenaires", division: "All Age" },
  Guardians: { key: "001j000000iwx9saad", name: "Guardians", division: "Open Class" },
  HawthorneCaballeros: { key: "0015b00001mpuwcaak", name: "Hawthorne Caballeros", division: "All Age" },
  HeatWave: { key: "001j000000iwx9taad", name: "Heat Wave", division: "Open Class" },
  HighSchoolAffiliatedToBIT: { key: "high-school-affiliated-to-bit", name: "High School Affiliated to BIT", division: "Open Class" },
  Impulse: { key: "001j000000iwx9uaad", name: "Impulse", division: "Open Class" },
  Incognito: { key: "001j000000iwx9vaad", name: "Incognito", division: "Open Class" },
  JerseySurf: { key: "001j000000iwx9waad", name: "Jersey Surf", division: "World Class" },
  Jubal: { key: "001j000000iwx9yaad", name: "Jubal", division: "World Class" },
  Kilties: { key: "kilties", name: "Kilties", division: "All Age" },
  Legends: { key: "001j000000iwxa0aal", name: "Legends", division: "Open Class" },
  LesStentors: { key: "001j000000iwxa1aal", name: "Les Stentors", division: "Open Class" },
  LouisianaStars: { key: "001j000000iwxa2aal", name: "Louisiana Stars", division: "Open Class" },
  MadisonScouts: { key: "001j000000i6lenaa3", name: "Madison Scouts", division: "World Class" },
  Mandarins: { key: "001j000000iwxa3aal", name: "Mandarins", division: "World Class" },
  MusicCity: { key: "001j000000iwxa5aal", name: "Music City", division: "World Class" },
  NewYorkSkyliners: { key: "0015b00002e2gtpaa3", name: "New York Skyliners", division: "All Age" },
  OregonCrusaders: { key: "001j000000iwxa6aal", name: "Oregon Crusaders", division: "World Class" },
  PacificCrest: { key: "001j000000iwxa7aal", name: "Pacific Crest", division: "World Class" },
  Patria: { key: "patria", name: "Patria", division: "World Class" },
  PhantomRegiment: { key: "001j000000h3xrnaav", name: "Phantom Regiment", division: "World Class" },
  Pioneer: { key: "001j000000iwxa8aal", name: "Pioneer", division: "World Class" },
  RacineScouts: { key: "racine-scouts", name: "Racine Scouts", division: "Open Class" },
  Raiders: { key: "001j000000iwxaaaa1", name: "Raiders", division: "Open Class" },
  ReadingBuccaneers: { key: "0010a00001e2pfhaam", name: "Reading Buccaneers", division: "All Age" },
  RiverCityRhythm: { key: "001j000000qzs1qaaf", name: "River City Rhythm", division: "Open Class" },
  RoguesHollowRegiment: { key: "001j000000cap31aaa", name: "Rogues Hollow Regiment", division: "All Age" },
  SantaClaraVanguard: { key: "001j000000h3xwcaav", name: "Santa Clara Vanguard", division: "World Class" },
  SeattleCascades: { key: "001j000000iwx93aad", name: "Seattle Cascades", division: "World Class" },
  Shadow: { key: "001j0000012tpxmaa2", name: "Shadow", division: "Open Class" },
  SoCalDream: { key: "socal-dream", name: "SoCal Dream", division: "All Age" },
  SouthernKnights: { key: "southern-knights", name: "Southern Knights", division: "All Age" },
  Southwind: { key: "001j000000iwxabaa1", name: "Southwind", division: "Open Class" },
  Spartans: { key: "001j000000iwxacaa1", name: "Spartans", division: "Open Class" },
  SpiritOfAtlanta: { key: "001j000000iwxadaa1", name: "Spirit of Atlanta", division: "World Class" },
  Sunrisers: { key: "0010a00001iqmzuaah", name: "Sunrisers", division: "All Age" },
  TaipeiYuehfu: { key: "taipei-yuehfu", name: "Taipei Yuehfu", division: "World Class" },
  TheAcademy: { key: "001j000000iwxaeaa1", name: "The Academy", division: "World Class" },
  TheBattalion: { key: "001j0000012y6bqaac", name: "The Battalion", division: "Open Class" },
  TheCadets: { key: "001j000000i6kfgaan", name: "The Cadets", division: "World Class" },
  TheCavaliers: { key: "001j000000iwxafaa1", name: "The Cavaliers", division: "World Class" },
  TheCompany: { key: "001j0000012sixfaaa", name: "The Company", division: "World Class" },
  Thunder: { key: "001j000000iwxaiaa1", name: "Thunder", division: "Open Class" },
  Troopers: { key: "001j000000iwxajaa1", name: "Troopers", division: "World Class" },
  VanguardCadets: { key: "001j000000iwxakaa1", name: "Vanguard Cadets", division: "Open Class" },
  Vessel: { key: "001j000000iwx95aad", name: "Vessel", division: "Open Class" },
  Watchmen: { key: "001j000000f17bwaaa", name: "Watchmen", division: "Open Class" },
  WhiteSabers: { key: "001jw00000d0zlniaj", name: "White Sabers", division: "All Age" },
  Unknown: { key: 'unknown', name: 'Unknown', division: 'World Class', unknown: true },
} as const satisfies Record<string, Corps>;

// Freeze the instances (const-object literal above is compile-time readonly only).
for (const c of Object.values(GENERATED_CORPS)) Object.freeze(c);
Object.freeze(GENERATED_CORPS);

export type GeneratedCorpsId = keyof typeof GENERATED_CORPS;

/** Canonical names + aliases that {@link matchCorps} resolves — the strict Corps.named() domain. */
export type KnownCorpsName =
  | "Alisal CAN Marching Band & Drum Corps"
  | "Alisal Community Arts Network Marching Band"
  | "Alisal Union School District All-Star Academy"
  | "Alisal Union School District Marching Band"
  | "Alisal USD All-Star Drum Corps"
  | "Alliance"
  | "Apogee Music Center"
  | "Arsenal"
  | "Arsenal DBC"
  | "Arsenal Drum & Bugle Corps"
  | "Arsenal Drum and Bugle Corps"
  | "Atlanta CV"
  | "Beijing 57 High School"
  | "Blue Devils"
  | "Blue Devils B"
  | "Blue Devils C"
  | "Blue Knights"
  | "Blue Saints"
  | "Blue Stars"
  | "Bluecoats"
  | "Bluecoats Rhythm IN BLUE"
  | "Boston Crusaders"
  | "Bushwackers"
  | "Bushwackers Drum Corps"
  | "Cadets 2"
  | "Cadets 2 Drum & Bugle Corps"
  | "Cadets 2 Drum and Bugle Corps"
  | "Cadets2"
  | "Calgary Round-Up Band"
  | "Calgary Stampede Showband"
  | "Calgary Stetson Show Band"
  | "Carolina Crown"
  | "Carolina Gold"
  | "Chien Kuo"
  | "Cincinnati Tradition"
  | "City Sound"
  | "City Sound Drum & Bugle Corps"
  | "City Sound Drum and Bugle Corps"
  | "Coastal Surge"
  | "Colt Cadets"
  | "Colts"
  | "Columbians"
  | "Columbus Saints"
  | "Connecticut Hurricanes"
  | "Crossmen"
  | "CT Hurricanes"
  | "Encorps"
  | "Encorps Drum & Bugle Corps"
  | "Encorps Marching Music"
  | "Erie Thunderbirds"
  | "Eruption"
  | "Eruption Drum & Bugle Corps"
  | "Fusion Core"
  | "Genesis"
  | "Gita Surosowan Banten"
  | "Gold"
  | "Golden Empire"
  | "Govenaires"
  | "Green Beret"
  | "Guardians"
  | "Hawthorne Caballeros"
  | "Heat Wave"
  | "High School Affiliated to BIT"
  | "Hurricanes"
  | "Impulse"
  | "Incognito"
  | "Incognito DBC"
  | "Incognito Drum & Bugle Corps"
  | "Jersey Surf"
  | "Jubal"
  | "Jubal Drum & Bugle Corps"
  | "Jubal Drum and Bugle Corps"
  | "Kilties"
  | "Latrobe Apogee"
  | "Latrobe Music Center"
  | "Legends"
  | "Les Stentors"
  | "Louisiana Stars"
  | "Madison Scouts"
  | "Mandarins"
  | "MBI"
  | "Minnesota Brass Inc"
  | "Music City"
  | "New York Skyliners"
  | "Northern Lights"
  | "Oregan Crusaders"
  | "Oregon Crusaders"
  | "Oregon Crusaders Drum & Bugle Corps"
  | "Oregon Crusaders Drum and Bugle Corps"
  | "Pacific Crest"
  | "Patria"
  | "Phantom Regiment"
  | "Pioneer"
  | "Pioneer DBC"
  | "Pioneer Drum & Bugle Corps"
  | "Pioneer Drum and Bugle Corps"
  | "Pioneer Drum Corps"
  | "Racine Scouts"
  | "Racine Scouts Drum & Bugle Corps"
  | "Racine Scouts Drum and Bugle Corps"
  | "Raiders"
  | "Reading Buccaneers"
  | "River City Rhythm"
  | "Rogues Hollow Regiment"
  | "Santa Clara Vanguard"
  | "Santa Clara Vanguard Cadets"
  | "SCV Cadets"
  | "Seattle Cascades"
  | "Shadow"
  | "Shadow DBC"
  | "Shadow Drum & Bugle Corps"
  | "Skyliners"
  | "SoCal Dream"
  | "Southern Knights"
  | "Southwind"
  | "Spartans"
  | "Spirit of Atlanta"
  | "Spokane Thunder"
  | "Sunrisers"
  | "Taipei Yuehfu"
  | "The Academy"
  | "The Battalion"
  | "The Blue Way Middle School Honor Band"
  | "The Blue Way Summer Arts Camp"
  | "The Cadets"
  | "The Cavaliers"
  | "The CO"
  | "The Company"
  | "THE COMPANY"
  | "The Company Performance Ensemble"
  | "Thunder"
  | "Thunder Drum & Bugle Corps"
  | "Thunder Drum and Bugle Corps"
  | "Troopers"
  | "Vanguard Cadets"
  | "Vanguard Cadets Drum & Bugle Corps"
  | "Vanguard Cadets Drum and Bugle Corps"
  | "Vessel"
  | "Watchmen"
  | "White Sabers";
